# Generated by Django 6.0 on 2025-12-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
