# Generated by Django 6.0 on 2025-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_desc_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
